from typing import Optional
import numpy as np
from numpy.typing import NDArray

def sgemm(A: NDArray[np.float32], B: NDArray[np.float32],
          C: Optional[NDArray[np.float32]] = ..., alpha: float = ..., beta: float = ...) -> NDArray[np.float32]: ...

def gelu(x: NDArray[np.float32]) -> NDArray[np.float32]: ...

def gelu_inplace(x: NDArray[np.float32]) -> None: ...

def relu(x: NDArray[np.float32]) -> NDArray[np.float32]: ...

def silu(x: NDArray[np.float32]) -> NDArray[np.float32]: ...

def softmax(x: NDArray[np.float32], axis: int = ...) -> NDArray[np.float32]: ...

def detected_isa() -> str: ...

def build_info() -> dict[str, str | bool]: ...

def set_num_threads(n: int) -> None: ...

def get_num_threads() -> int: ...

def is_aligned(arr: np.ndarray) -> bool: ...
